### ISSUE TITLE
Text font weight: thin vs. regular

### ISSUE THREAD

**Issue by imphil** [fossi-foundation/fossi-foundation-web#1]
It's unclear what the default font weight for text should be. The style guide is inconsistent w.r.t. 500 (regular) and 100 (thin).

For example, take this block of text:

Style guide:
![grafik](https://user-images.githubusercontent.com/1467123/214736701-da5fbe5f-bbe6-4601-a1d6-9cb0c23a70cc.png)

Current coding:

![grafik](https://user-images.githubusercontent.com/1467123/214736249-733cd6d7-6807-4b13-8436-4b797444f4eb.png)

At the same time, the style guide says paragraph text should use weight 100 (thin), while the inspection says thin, 500 (which doesn't exist). What's right? (Picture from the inspector sidebar of https://zeroheight.com/822235964/p/09285f-homepage/i/104127505 for the text shown above.)

![grafik](https://user-images.githubusercontent.com/1467123/214736866-ed756f9b-53ce-4197-bae5-388a5c31e65f.png)

@asherdub can you confirm the correct font weight, and update the style guide accordingly if necessary.

**Comment by asherdub** [comment]
@imphil Paragraph weight should be 500 / medium. This is the only font style that the integration has read incorrectly. I have added a bold note to the Tokens / Typography section of the web design system. See https://zeroheight.com/822235964/p/48281f-typography/t/729e31

**Comment by imphil** [comment]
Thanks! Is there a way to fix the weight displayed in ZeroHeight so that we can avoid the conflicting information being displayed?


![image](https://user-images.githubusercontent.com/1467123/220197583-be41aff9-71af-411c-871d-e19ad854be95.png)

**Comment by asherdub** [comment]
In Figma I have changed this style to slightly thinner font-weight 400 (regular). It now displays the correct weight of 400. 
This affects 3 components: Longform content, Signpost with icon and Supporting Content.

**Comment by imphil** [comment]
Great, thanks! Using 400/normal for paragraph text makes my life much easier!

**Comment by imphil** [comment]
The font weights are now implemented in the preview at https://fossi-foundation-preview.netlify.app.

There are two cases where the style guide needs updates to refer to "regular" instead of "medium":

* https://zeroheight.com/822235964/p/852315-typography ("Use "Public Sans Medium" for longform body text such as article copy.")
* https://zeroheight.com/822235964/p/814285-presentation-slides

Should that be updated as well, @asherdub?

**Comment by asherdub** [comment]
@imphil Done. Both pages now reference "regular" instead of "medium" weight.

**Comment by imphil** [comment]
Thanks, let's consider this one resolved then!
