### ISSUE TITLE
Latch-up 2024 site not working

### ISSUE THREAD

**Issue by sifferman** [fossi-foundation/fossi-foundation-web#104]
Hello.

Could you double check that the latch-up 2024 website is working?

<https://fossi-foundation.org/latch-up/2024> results in "Page not found"

and clicking on Latch-Up 2024 on <https://fossi-foundation.org/events/archive> results in "Sorry this page does not exist =(".

Thanks!

**Comment by juliusbaxter** [comment]
Hi Ethan, yes we're aware of this. I don't understand why this is happening. I've asked for help from @imphil. Something broke while I added the ORConf site. 😢

**Comment by imphil** [comment]
Fixed by https://github.com/fossi-foundation/fossi-foundation-web/pull/105
