### ISSUE TITLE
Page load times: optimize blog overview page

### ISSUE THREAD

**Issue by imphil** [fossi-foundation/fossi-foundation-web#17]
The blog overview page is the slowest page to load (https://fossi-foundation-preview.netlify.app/news). Look at ways for improvement. (It's probably a mixture of scripting and resizing images properly.)

**Comment by imphil** [comment]
Look at using https://github.com/nuxt/image once it has left the RC stage, we don't have a strong enough need to be beta testers.

**Comment by Khushikela29** [comment]
Hii !! 
Are you still facing the issues if yes , how can i help you fix the issue??

**Comment by imphil** [comment]
The frontpage (mobile view) went from

![image](https://github.com/fossi-foundation/fossi-foundation-web/assets/1467123/41b9bebb-7fb8-4b70-801d-5af83733742a)

![image](https://github.com/fossi-foundation/fossi-foundation-web/assets/1467123/17fad913-741e-445f-85eb-e2009ccd64d9)


The blog overview page is now at

![image](https://github.com/fossi-foundation/fossi-foundation-web/assets/1467123/3c436c9b-02a7-4979-a69d-0c912c096260)


Even though it has tons of images, the blog overview page now loads significantly faster.
