### ISSUE TITLE
El Correo Image missing

### ISSUE THREAD

**Issue by imphil** [fossi-foundation/fossi-foundation-web#2]
The Homepage section in the style guide has a new logo for El Correo Libre (https://zeroheight.com/822235964/p/09285f-homepage). 

@asherdub can you send me this logo? I didn't find it in any of the downloadable assets.

**Comment by asherdub** [comment]
Logo wasn't added as unsure if this had been approved or just for mockup. SVG attached:
[ecl-logo-fossi.zip](https://github.com/fossi-foundation/fossi-foundation-web/files/10511534/ecl-logo-fossi.zip)

**Comment by imphil** [comment]
Thanks, the logo works well for our purpose, I'll just use it as-is for now. Thanks!
