### ISSUE TITLE
Letter spacing of headings

### ISSUE THREAD

**Issue by imphil** [fossi-foundation/fossi-foundation-web#3]
Headings do not specify a letter spacing property in the style guide. However, looking at the inspector in ZeroHeight, I see that all of them set it.

For example, display h1 sets letter spacing to -2.43px when inspecting https://zeroheight.com/822235964/p/09285f-homepage:

![grafik](https://user-images.githubusercontent.com/1467123/214738333-5a2eae0f-ea5e-4784-acca-59caf360b8b4.png)

https://zeroheight.com/822235964/p/48281f-typography says:

![grafik](https://user-images.githubusercontent.com/1467123/214738548-fb9039e1-7539-4907-8ee2-8612838a8cea.png)

Is the letter spacing property missing from the style guide, or should we not apply any spacing @asherdub?

**Comment by asherdub** [comment]
Letter spacing should be applied. The font spec is pulled from the linked Figma design file. The integration might not show everything.  The brand guide states to use tighter letter spacing and line-height for headings and looser for paragraphs.  Tailwind gives you classes to use for this.   

For h2-h6 use .tracking-tight and .leading-tight.  
For h1 use .tracking-tighter and .leading-none.  
For paragraphs use .tracking-normal and .leading-normal

**Comment by asherdub** [comment]
@imphil Style guide is correct. All headings should use leading-tight except display h1 which is leading-none. Apologies if my last comment was confusing.

You're correct that .leading-tight is 125%. This should be changed to 110% to match the style guide. You can change this in tailwind.config.js. add the following to the extend key in your config:

`extend: {
      lineHeight: {
        'tight': '1.1',
      }
    }`

or if you want to keep leading-tight unchanged, make a new class:

`extend: {
      lineHeight: {
        'tighter': '1.1',
      }
    }`

**Comment by imphil** [comment]
Thanks, fixed!
