### ISSUE TITLE
Document older Latchup schedules

### ISSUE THREAD

**Issue by xobs** [fossi-foundation/fossi-foundation-web#31]
I'm trying to find a talk that was given at Latchup 2023. I don't see it on Youtube, and links on search engines are now dead -- for example, none of these links -- which are the top hits when I search for "latchup 2023" -- work:

![image](https://github.com/fossi-foundation/fossi-foundation-web/assets/238325/ee4e4a58-47e6-48e1-9a89-4d840b8a3e76)

Please provide a resource for looking up older schedules. For example, I know the talk I want was presented on the last day, but I can't find the schedule to see what it could have been.

**Comment by imphil** [comment]
Hi. Thanks for your interest in Latch-Up content. I do not intend to bring all the old Latch-Up content over to the new page. However, you can find it at https://www-archive.fossi-foundation.org/latchup/. And, of course, we're accepting pull requests if you'd like to port some of the older content over!
