### ISSUE TITLE
Only import relevant icons

### ISSUE THREAD

**Issue by imphil** [fossi-foundation/fossi-foundation-web#4]
We currently import a fair number of icons from phosphor and fontawesome, leading to a rather massive bundle (~5 MB). Only import what we need to get this size down.

**Comment by asherdub** [comment]
@imphil I suggest using the necessary icons inline. Upload to https://icomoon.io/app/ which will generate a sprite for you. Let me know the icons you wish to use for first release and I can make it for you if needed.

**Comment by imphil** [comment]
I now switched to https://github.com/antfu/unplugin-icons, which seems to do the trick.
