### ISSUE TITLE
Enhancement : Updated footer layout for better user experience 

### ISSUE THREAD

**Issue by rufevean** [fossi-foundation/fossi-foundation-web#43]
![Slide 4_3 - 1](https://github.com/fossi-foundation/fossi-foundation-web/assets/95273312/fb0579eb-58da-4d7e-a5aa-3715a52630c2)

The objective is to achieve better symmetry with the footer and overall better user experience. 
I am willing to contribute to the implementation of this enhancement and have already created a design in Figma. If you assign this issue to me, I will proceed with coding the changes.

**Comment by imphil** [comment]
Hi @rufevean, thanks for stopping by here.

The website follows our style guide, which has specified the footer as it is implemented today. We will leave it as-is therefore.
