### ISSUE TITLE
Sub-navigation

### ISSUE THREAD

**Issue by imphil** [fossi-foundation/fossi-foundation-web#7]
The placement options of the sub-navigation, as described at https://zeroheight.com/822235964/p/778a1b-navigation are not ideal.

* Positioning the navigation below the main navigation bar (one option in the style guide) has the benefit of consistent vertical positioning (users can navigate from one sub-page to the next by only moving their mouse to the right), but it looks somewhat lost in the structure.
* Positioning the navigation bar below the page header section looks visually more pleasing (to me), but is semantically strange (the menu items do not refer to sub-items of the page header, but sub-items to the main category) and suffers from moving around vertically depending on the size of the page header.

For now I chose slightly better (IMO) positioning above the page header, but I'm not really happy with that.

Beyond positioning, we need to think about the phone view of the sub-navigation bar. Currently, it easily stretches horizontally beyond the viewport, causing horizontal scroll.

I'm not sure if there is an easy fix for that, or if we need to rethink the subnavigation concept (e.g. to use drop-downs within the main navigation menu, etc.)

**Comment by asherdub** [comment]
@imphil Try an ultraviolet sub nav for better separation from the man navigation.
![Screenshot 2023-03-24 at 13-58-11 About us](https://user-images.githubusercontent.com/11976595/227543421-3ef79bba-26ed-4aef-8a1f-7f2052cff163.png)

For mobile, I often collapse the sub-nav behind a menu button. See the examples below:
![Screenshot 2023-03-24 at 14-04-20 Creative Care Ltd Features](https://user-images.githubusercontent.com/11976595/227543822-8dd52885-cae1-49bf-8dd3-2cca4dc45882.png)
![Screenshot 2023-03-24 at 14-05-16 Creative Care Ltd Features](https://user-images.githubusercontent.com/11976595/227543852-f80860e6-cfc8-4d4d-b82c-7376046c03b3.png)

Dropdown menus for a short sub-nav are generally avoided as they are not good for accessibility.

**Comment by imphil** [comment]
We now have a working sub nav. I kept the white background, the ultraviolet doesn't work super well either IMO. For the phone view I simply switch from a column to a row layout, which works reasonably well. Let me know what you think, @asherdub!

**Comment by imphil** [comment]
@asherdub had a look and I his comments are addressed in #20, closing this issue here.
